// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appHealth: () => __TAURI_INVOKE<string>("app_health"),
	listAccounts: () => typedError<Account[], string>(__TAURI_INVOKE("list_accounts")),
	resolveEndpoints: (email: string) => __TAURI_INVOKE<Endpoints>("resolve_endpoints", { email }),
	addAccount: (email: string, displayName: string, password: string, endpoints: Endpoints) => typedError<Account, string>(__TAURI_INVOKE("add_account", { email, displayName, password, endpoints })),
	removeAccount: (accountId: number) => typedError<null, string>(__TAURI_INVOKE("remove_account", { accountId })),
	reorderAccounts: (orderedIds: number[]) => typedError<null, string>(__TAURI_INVOKE("reorder_accounts", { orderedIds })),
	beginReauth: (accountId: number) => typedError<null, string>(__TAURI_INVOKE("begin_reauth", { accountId })),
	beginGoogleOauth: () => typedError<Account, string>(__TAURI_INVOKE("begin_google_oauth")),
	listFolders: (accountId: number) => typedError<Folder[], string>(__TAURI_INVOKE("list_folders", { accountId })),
	listMessages: (folderId: number, limit: number, offset: number) => typedError<MessageHeader[], string>(__TAURI_INVOKE("list_messages", { folderId, limit, offset })),
	getMessageBody: (messageId: number) => typedError<MessageBody, string>(__TAURI_INVOKE("get_message_body", { messageId })),
	sanitizeMessageHtml: (html: string) => __TAURI_INVOKE<SanitizedHtml>("sanitize_message_html", { html }),
	setMessageFlags: (messageId: number, flag: MessageFlag, value: boolean) => typedError<null, string>(__TAURI_INVOKE("set_message_flags", { messageId, flag, value })),
	markMessageSeen: (messageId: number) => typedError<null, string>(__TAURI_INVOKE("mark_message_seen", { messageId })),
	listThreads: (folderId: number, limit: number, offset: number) => typedError<ThreadSummary[], string>(__TAURI_INVOKE("list_threads", { folderId, limit, offset })),
	listThreadMessages: (threadId: number) => typedError<MessageHeader[], string>(__TAURI_INVOKE("list_thread_messages", { threadId })),
	enqueueSend: (draftId: number) => typedError<null, string>(__TAURI_INVOKE("enqueue_send", { draftId })),
	startReply: (messageId: number, mode: string) => typedError<OutgoingMessage, string>(__TAURI_INVOKE("start_reply", { messageId, mode })),
	saveDraft: (accountId: number, draftId: number | null, message: OutgoingMessage) => typedError<number, string>(__TAURI_INVOKE("save_draft", { accountId, draftId, message })),
	getDraft: (draftId: number) => typedError<OutgoingMessage, string>(__TAURI_INVOKE("get_draft", { draftId })),
	listDrafts: (accountId: number) => typedError<number[], string>(__TAURI_INVOKE("list_drafts", { accountId })),
	discardDraft: (draftId: number) => typedError<null, string>(__TAURI_INVOKE("discard_draft", { draftId })),
	listSignatures: (accountId: number) => typedError<Signature[], string>(__TAURI_INVOKE("list_signatures", { accountId })),
	pickAttachment: () => typedError<OutgoingAttachment[], string>(__TAURI_INVOKE("pick_attachment")),
	listSmartFolder: (kind: SmartFolderKind, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("list_smart_folder", { kind, limit, offset })),
	searchMessages: (query: string, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("search_messages", { query, limit, offset })),
	listLabels: () => typedError<Label[], string>(__TAURI_INVOKE("list_labels")),
	createLabel: (name: string, color: string) => typedError<Label, string>(__TAURI_INVOKE("create_label", { name, color })),
	renameLabel: (id: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_label", { id, name })),
	setLabelColor: (id: number, color: string) => typedError<null, string>(__TAURI_INVOKE("set_label_color", { id, color })),
	deleteLabel: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_label", { id })),
	setMessageLabels: (labelId: number, messageIds: number[], applied: boolean) => typedError<null, string>(__TAURI_INVOKE("set_message_labels", { labelId, messageIds, applied })),
	labelsForMessages: (messageIds: number[]) => typedError<([number, Label])[], string>(__TAURI_INVOKE("labels_for_messages", { messageIds })),
	listMessagesByLabel: (labelId: number, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("list_messages_by_label", { labelId, limit, offset })),
	getSettings: () => typedError<([string, string])[], string>(__TAURI_INVOKE("get_settings")),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
};

/** Events */
export const events = {
	accountAuthChanged: makeEvent<AccountAuthChanged>("account-auth-changed"),
	mailboxChanged: makeEvent<MailboxChanged>("mailbox-changed"),
	newMessages: makeEvent<NewMessages>("new-messages"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
export type Account = {
	id: number,
	email: string,
	display_name: string,
	provider_type: ProviderType,
	color: string | null,
	position: number,
	requires_reauth: boolean,
};

export type AccountAuthChanged = {
	account_id: number,
	requires_reauth: boolean,
};

export type Endpoints = {
	imap_host: string,
	imap_port: number,
	imap_tls: boolean,
	smtp_host: string,
	smtp_port: number,
	smtp_tls: boolean,
};

export type Folder = {
	id: number,
	account_id: number,
	remote_path: string,
	name: string,
	folder_type: FolderType,
	unread_count: number,
	total_count: number,
};

export type FolderType = "inbox" | "sent" | "drafts" | "trash" | "spam" | "archive" | "custom";

export type Label = {
	id: number,
	name: string,
	color: string,
};

export type MailboxChanged = {
	account_id: number,
	folder_id: number,
};

export type MessageBody = {
	message_id: number,
	text_plain: string | null,
	text_html: string | null,
};

export type MessageFlag = "seen" | "flagged";

export type MessageHeader = {
	id: number,
	account_id: number,
	folder_id: number,
	subject: string,
	from_address: string,
	from_name: string | null,
	date: number,
	seen: boolean,
	flagged: boolean,
	has_attachments: boolean,
	snippet: string,
};

export type NewMessages = {
	account_id: number,
	folder_id: number,
	count: number,
};

export type OutgoingAttachment = {
	filename: string,
	mime_type: string,
	blob_ref: string,
	content_id: string | null,
};

export type OutgoingMessage = {
	from_address: string,
	from_name: string | null,
	to: string[],
	cc: string[],
	bcc: string[],
	subject: string,
	text_body: string,
	html_body: string | null,
	in_reply_to: string | null,
	references: string[],
	attachments: OutgoingAttachment[],
};

export type ProviderType = "imap_password" | "google_oauth";

export type SanitizedHtml = {
	html: string,
	blocked_remote_content: boolean,
};

export type Signature = {
	id: number,
	name: string,
	html: string,
	is_default: boolean,
};

export type SmartFolderKind = "all_inboxes" | "unread" | "flagged" | "snoozed";

export type SmartMessageRow = {
	message_id: number,
	account_id: number,
	folder_id: number,
	account_color: string | null,
	from_address: string,
	from_name: string | null,
	subject: string,
	date: number,
	seen: boolean,
	flagged: boolean,
	has_attachments: boolean,
	snippet: string,
	snooze_wake_at: number | null,
};

export type SyncProgress = {
	account_id: number,
	folder_id: number,
	fetched: number,
	total: number,
};

export type ThreadSummary = {
	thread_id: number,
	account_id: number,
	subject: string,
	last_date: number,
	message_count: number,
	unread_count: number,
	participants: string[],
	snippet: string,
	has_attachments: boolean,
	flagged: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

