// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appHealth: () => __TAURI_INVOKE<string>("app_health"),
	listAccounts: () => typedError<Account[], string>(__TAURI_INVOKE("list_accounts")),
	resolveEndpoints: (email: string) => __TAURI_INVOKE<Endpoints>("resolve_endpoints", { email }),
	addAccount: (email: string, displayName: string, password: string, endpoints: Endpoints) => typedError<Account, string>(__TAURI_INVOKE("add_account", { email, displayName, password, endpoints })),
	removeAccount: (accountId: number) => typedError<null, string>(__TAURI_INVOKE("remove_account", { accountId })),
	reorderAccounts: (orderedIds: number[]) => typedError<null, string>(__TAURI_INVOKE("reorder_accounts", { orderedIds })),
	getAccountEndpoints: (accountId: number) => typedError<Endpoints, string>(__TAURI_INVOKE("get_account_endpoints", { accountId })),
	updateAccount: (accountId: number, displayName: string, color: string | null, endpoints: {
	imap_host: string,
	imap_port: number,
	imap_tls: boolean,
	smtp_host: string,
	smtp_port: number,
	smtp_tls: boolean,
} | null, password: string | null) => typedError<Account, string>(__TAURI_INVOKE("update_account", { accountId, displayName, color, endpoints, password })),
	beginReauth: (accountId: number) => typedError<null, string>(__TAURI_INVOKE("begin_reauth", { accountId })),
	beginGoogleOauth: () => typedError<Account, string>(__TAURI_INVOKE("begin_google_oauth")),
	listFolders: (accountId: number) => typedError<Folder[], string>(__TAURI_INVOKE("list_folders", { accountId })),
	markFolderRead: (folderId: number) => typedError<null, string>(__TAURI_INVOKE("mark_folder_read", { folderId })),
	renameFolder: (folderId: number, newName: string) => typedError<null, string>(__TAURI_INVOKE("rename_folder", { folderId, newName })),
	deleteFolder: (folderId: number) => typedError<null, string>(__TAURI_INVOKE("delete_folder", { folderId })),
	createSubfolder: (parentFolderId: number, name: string) => typedError<null, string>(__TAURI_INVOKE("create_subfolder", { parentFolderId, name })),
	listMessages: (folderId: number, limit: number, offset: number) => typedError<MessageHeader[], string>(__TAURI_INVOKE("list_messages", { folderId, limit, offset })),
	getMessageBody: (messageId: number) => typedError<MessageBody, string>(__TAURI_INVOKE("get_message_body", { messageId })),
	sanitizeMessageHtml: (html: string) => __TAURI_INVOKE<SanitizedHtml>("sanitize_message_html", { html }),
	renderMessageHtml: (messageId: number, forceLoadRemote: boolean) => typedError<RenderedMessage, string>(__TAURI_INVOKE("render_message_html", { messageId, forceLoadRemote })),
	messageRecipients: (messageId: number) => typedError<MessageRecipients, string>(__TAURI_INVOKE("message_recipients", { messageId })),
	listAttachments: (messageId: number) => typedError<Attachment[], string>(__TAURI_INVOKE("list_attachments", { messageId })),
	saveAttachment: (attachmentId: number) => typedError<boolean, string>(__TAURI_INVOKE("save_attachment", { attachmentId })),
	openAttachment: (attachmentId: number) => typedError<null, string>(__TAURI_INVOKE("open_attachment", { attachmentId })),
	setMessageFlags: (messageId: number, flag: MessageFlag, value: boolean) => typedError<null, string>(__TAURI_INVOKE("set_message_flags", { messageId, flag, value })),
	archiveMessages: (messageIds: number[]) => typedError<null, string>(__TAURI_INVOKE("archive_messages", { messageIds })),
	deleteMessages: (messageIds: number[]) => typedError<null, string>(__TAURI_INVOKE("delete_messages", { messageIds })),
	undoMove: (messageIds: number[]) => typedError<null, string>(__TAURI_INVOKE("undo_move", { messageIds })),
	moveMessages: (messageIds: number[], targetFolderId: number) => typedError<null, string>(__TAURI_INVOKE("move_messages", { messageIds, targetFolderId })),
	messageIdsForThreads: (threadIds: number[]) => typedError<number[], string>(__TAURI_INVOKE("message_ids_for_threads", { threadIds })),
	markMessageSeen: (messageId: number) => typedError<null, string>(__TAURI_INVOKE("mark_message_seen", { messageId })),
	listThreads: (folderId: number, limit: number, offset: number) => typedError<ThreadSummary[], string>(__TAURI_INVOKE("list_threads", { folderId, limit, offset })),
	listThreadMessages: (threadId: number) => typedError<MessageHeader[], string>(__TAURI_INVOKE("list_thread_messages", { threadId })),
	threadForMessage: (messageId: number) => typedError<number, string>(__TAURI_INVOKE("thread_for_message", { messageId })),
	enqueueSend: (draftId: number) => typedError<null, string>(__TAURI_INVOKE("enqueue_send", { draftId })),
	listSendErrors: () => typedError<SendError[], string>(__TAURI_INVOKE("list_send_errors")),
	retrySend: (id: number) => typedError<null, string>(__TAURI_INVOKE("retry_send", { id })),
	dismissSendError: (id: number) => typedError<null, string>(__TAURI_INVOKE("dismiss_send_error", { id })),
	startReply: (messageId: number, mode: string) => typedError<OutgoingMessage, string>(__TAURI_INVOKE("start_reply", { messageId, mode })),
	saveDraft: (accountId: number, draftId: number | null, message: OutgoingMessage) => typedError<number, string>(__TAURI_INVOKE("save_draft", { accountId, draftId, message })),
	getDraft: (draftId: number) => typedError<OutgoingMessage, string>(__TAURI_INVOKE("get_draft", { draftId })),
	listDrafts: (accountId: number) => typedError<number[], string>(__TAURI_INVOKE("list_drafts", { accountId })),
	discardDraft: (draftId: number) => typedError<null, string>(__TAURI_INVOKE("discard_draft", { draftId })),
	listSignatures: (accountId: number) => typedError<Signature[], string>(__TAURI_INVOKE("list_signatures", { accountId })),
	createSignature: (accountId: number, name: string, html: string, makeDefault: boolean, isHtml: boolean) => typedError<Signature, string>(__TAURI_INVOKE("create_signature", { accountId, name, html, makeDefault, isHtml })),
	updateSignature: (id: number, name: string, html: string, isHtml: boolean) => typedError<null, string>(__TAURI_INVOKE("update_signature", { id, name, html, isHtml })),
	setDefaultSignature: (accountId: number, id: number) => typedError<null, string>(__TAURI_INVOKE("set_default_signature", { accountId, id })),
	deleteSignature: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_signature", { id })),
	pickAttachment: () => typedError<OutgoingAttachment[], string>(__TAURI_INVOKE("pick_attachment")),
	listSmartFolder: (kind: SmartFolderKind, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("list_smart_folder", { kind, limit, offset })),
	searchMessages: (query: string, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("search_messages", { query, limit, offset })),
	listLabels: () => typedError<Label[], string>(__TAURI_INVOKE("list_labels")),
	createLabel: (name: string, color: string) => typedError<Label, string>(__TAURI_INVOKE("create_label", { name, color })),
	renameLabel: (id: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_label", { id, name })),
	setLabelColor: (id: number, color: string) => typedError<null, string>(__TAURI_INVOKE("set_label_color", { id, color })),
	deleteLabel: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_label", { id })),
	setMessageLabels: (labelId: number, messageIds: number[], applied: boolean) => typedError<null, string>(__TAURI_INVOKE("set_message_labels", { labelId, messageIds, applied })),
	labelsForMessages: (messageIds: number[]) => typedError<([number, Label])[], string>(__TAURI_INVOKE("labels_for_messages", { messageIds })),
	listMessagesByLabel: (labelId: number, limit: number, offset: number) => typedError<SmartMessageRow[], string>(__TAURI_INVOKE("list_messages_by_label", { labelId, limit, offset })),
	getSettings: () => typedError<([string, string])[], string>(__TAURI_INVOKE("get_settings")),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
	snoozeMessages: (messageIds: number[], wakeAt: number) => typedError<null, string>(__TAURI_INVOKE("snooze_messages", { messageIds, wakeAt })),
	unsnoozeMessages: (messageIds: number[]) => typedError<null, string>(__TAURI_INVOKE("unsnooze_messages", { messageIds })),
	buildNewMailNotification: (folderId: number, count: number) => typedError<{
	title: string,
	body: string,
} | null, string>(__TAURI_INVOKE("build_new_mail_notification", { folderId, count })),
	refreshUnreadBadge: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("refresh_unread_badge", { enabled })),
	listRules: (accountId: number) => typedError<Rule[], string>(__TAURI_INVOKE("list_rules", { accountId })),
	createRule: (accountId: number, input: RuleInput) => typedError<Rule, string>(__TAURI_INVOKE("create_rule", { accountId, input })),
	updateRule: (ruleId: number, input: RuleInput) => typedError<null, string>(__TAURI_INVOKE("update_rule", { ruleId, input })),
	setRuleEnabled: (ruleId: number, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_rule_enabled", { ruleId, enabled })),
	deleteRule: (ruleId: number) => typedError<null, string>(__TAURI_INVOKE("delete_rule", { ruleId })),
};

/** Events */
export const events = {
	accountAuthChanged: makeEvent<AccountAuthChanged>("account-auth-changed"),
	mailboxChanged: makeEvent<MailboxChanged>("mailbox-changed"),
	newMessages: makeEvent<NewMessages>("new-messages"),
	prefetchProgress: makeEvent<PrefetchProgress>("prefetch-progress"),
	sendFailed: makeEvent<SendFailed>("send-failed"),
	snoozeWoke: makeEvent<SnoozeWoke>("snooze-woke"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
export type Account = {
	id: number,
	email: string,
	display_name: string,
	provider_type: ProviderType,
	color: string | null,
	position: number,
	requires_reauth: boolean,
};

export type AccountAuthChanged = {
	account_id: number,
	requires_reauth: boolean,
};

export type Attachment = {
	id: number,
	filename: string,
	mime_type: string,
	size: number,
};

export type ConditionField = "from" | "subject" | "recipient" | "has_attachment";

export type ConditionOp = "contains" | "is";

export type Endpoints = {
	imap_host: string,
	imap_port: number,
	imap_tls: boolean,
	smtp_host: string,
	smtp_port: number,
	smtp_tls: boolean,
};

export type Folder = {
	id: number,
	account_id: number,
	remote_path: string,
	name: string,
	folder_type: FolderType,
	unread_count: number,
	total_count: number,
};

export type FolderType = "inbox" | "sent" | "drafts" | "trash" | "spam" | "archive" | "custom";

export type Label = {
	id: number,
	name: string,
	color: string,
};

export type MailboxChanged = {
	account_id: number,
	folder_id: number,
};

export type MatchType = "all" | "any";

export type MessageBody = {
	message_id: number,
	text_plain: string | null,
	text_html: string | null,
};

export type MessageFlag = "seen" | "flagged";

export type MessageHeader = {
	id: number,
	account_id: number,
	folder_id: number,
	subject: string,
	from_address: string,
	from_name: string | null,
	date: number,
	seen: boolean,
	flagged: boolean,
	has_attachments: boolean,
	snippet: string,
};

export type MessageRecipients = {
	to: string[],
	cc: string[],
};

export type NewMessages = {
	account_id: number,
	folder_id: number,
	count: number,
};

export type NotificationContent = {
	title: string,
	body: string,
};

export type OutgoingAttachment = {
	filename: string,
	mime_type: string,
	blob_ref: string,
	content_id: string | null,
};

export type OutgoingMessage = {
	from_address: string,
	from_name: string | null,
	to: string[],
	cc: string[],
	bcc: string[],
	subject: string,
	text_body: string,
	html_body: string | null,
	in_reply_to: string | null,
	references: string[],
	attachments: OutgoingAttachment[],
};

export type PrefetchProgress = {
	account_id: number,
	done: number,
	total: number,
};

export type ProviderType = "imap_password" | "google_oauth";

export type RenderedMessage = {
	html: string | null,
	blocked_remote_content: boolean,
	remote_loaded: boolean,
};

export type Rule = {
	id: number,
	account_id: number,
	name: string,
	enabled: boolean,
	match_type: MatchType,
	conditions: RuleCondition[],
	actions: RuleAction[],
	position: number,
};

export type RuleAction = {
	kind: RuleActionKind,
	value: string,
};

export type RuleActionKind = "label" | "mark_read" | "flag" | "snooze";

export type RuleCondition = {
	field: ConditionField,
	op: ConditionOp,
	value: string,
};

export type RuleInput = {
	name: string,
	enabled: boolean,
	match_type: MatchType,
	conditions: RuleCondition[],
	actions: RuleAction[],
};

export type SanitizedHtml = {
	html: string,
	blocked_remote_content: boolean,
};

export type SendError = {
	id: number,
	account_id: number,
	subject: string,
	recipient: string,
	error: string,
	attempts: number,
	permanent: boolean,
};

export type SendFailed = {
	account_id: number,
	error: string,
};

export type Signature = {
	id: number,
	name: string,
	html: string,
	is_default: boolean,
	is_html: boolean,
};

export type SmartFolderKind = "all_inboxes" | "unread" | "flagged" | "snoozed";

export type SmartMessageRow = {
	message_id: number,
	account_id: number,
	folder_id: number,
	account_color: string | null,
	from_address: string,
	from_name: string | null,
	subject: string,
	date: number,
	seen: boolean,
	flagged: boolean,
	has_attachments: boolean,
	snippet: string,
	snooze_wake_at: number | null,
};

export type SnoozeWoke = {
	count: number,
};

export type SyncProgress = {
	account_id: number,
	folder_id: number,
	fetched: number,
	total: number,
};

export type ThreadSummary = {
	thread_id: number,
	account_id: number,
	subject: string,
	last_date: number,
	message_count: number,
	unread_count: number,
	participants: string[],
	snippet: string,
	has_attachments: boolean,
	flagged: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

