// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appHealth: () => __TAURI_INVOKE<string>("app_health"),
	listAccounts: () => typedError<Account[], string>(__TAURI_INVOKE("list_accounts")),
	addAccount: (account: NewAccount) => typedError<Account, string>(__TAURI_INVOKE("add_account", { account })),
};

/* Types */
export type Account = {
	id: number,
	email: string,
	display_name: string,
	provider_type: ProviderType,
	color: string | null,
	position: number,
};

export type NewAccount = {
	email: string,
	display_name: string,
	provider_type: ProviderType,
	color: string | null,
};

export type ProviderType = "imap_password" | "google_oauth";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

