pub mod commands;
pub mod events;
pub mod sink;
pub mod state;
pub mod tray;

use tauri_specta::{collect_commands, collect_events, Builder};

pub fn build_specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app_health,
            commands::list_accounts,
            commands::resolve_endpoints,
            commands::add_account,
            commands::remove_account,
            commands::reorder_accounts,
            commands::get_account_endpoints,
            commands::update_account,
            commands::begin_reauth,
            commands::begin_google_oauth,
            commands::list_folders,
            commands::mark_folder_read,
            commands::rename_folder,
            commands::delete_folder,
            commands::create_subfolder,
            commands::list_messages,
            commands::get_message_body,
            commands::sanitize_message_html,
            commands::render_message_html,
            commands::message_recipients,
            commands::list_attachments,
            commands::save_attachment,
            commands::save_all_attachments,
            commands::open_attachment,
            commands::meeting_invite,
            commands::respond_to_invite,
            commands::open_external_url,
            commands::set_message_flags,
            commands::archive_messages,
            commands::delete_messages,
            commands::undo_move,
            commands::move_messages,
            commands::message_ids_for_threads,
            commands::mark_message_seen,
            commands::list_threads,
            commands::list_thread_messages,
            commands::thread_for_message,
            commands::enqueue_send,
            commands::list_send_errors,
            commands::retry_send,
            commands::dismiss_send_error,
            commands::start_reply,
            commands::save_draft,
            commands::get_draft,
            commands::list_drafts,
            commands::discard_draft,
            commands::list_signatures,
            commands::create_signature,
            commands::update_signature,
            commands::set_default_signature,
            commands::delete_signature,
            commands::pick_attachment,
            commands::list_smart_folder,
            commands::search_messages,
            commands::list_labels,
            commands::create_label,
            commands::rename_label,
            commands::set_label_color,
            commands::delete_label,
            commands::set_message_labels,
            commands::labels_for_messages,
            commands::list_messages_by_label,
            commands::get_settings,
            commands::set_setting,
            commands::snooze_messages,
            commands::unsnooze_messages,
            commands::build_new_mail_notification,
            commands::refresh_unread_badge,
            commands::set_tray_enabled,
            commands::list_rules,
            commands::create_rule,
            commands::update_rule,
            commands::set_rule_enabled,
            commands::delete_rule,
        ])
        .events(collect_events![
            events::SyncProgress,
            events::NewMessages,
            events::MailboxChanged,
            events::AccountAuthChanged,
            events::SnoozeWoke,
            events::SendFailed,
            events::PrefetchProgress,
        ])
}
